"""Repository and ScanResult data models."""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class ScanResult:
    """Result of scanning a repository for structure and metadata."""

    languages: list[str] = field(default_factory=list)
    frameworks: list[str] = field(default_factory=list)
    file_count: int = 0
    size_bytes: int = 0
    ignored_dirs: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    estimated_index_time_ms: int = 0


@dataclass
class Repository:
    """A registered repository managed by RE:Track (RefinedEngine Track)."""

    id: str
    name: str
    source_type: str  # "github" | "local"
    local_path: str
    branch: str = "main"
    source_url: Optional[str] = None
    commit_hash: Optional[str] = None
    status: str = "registered"  # "registered" | "scanning" | "indexing" | "indexed" | "error"
    languages: list[str] = field(default_factory=list)
    frameworks: list[str] = field(default_factory=list)
    file_count: int = 0
    size_bytes: int = 0
    indexed_at: Optional[str] = None
    scan_result: Optional[ScanResult] = None
    error_message: Optional[str] = None
    created_at: str = ""  # ISO timestamp, auto-generated by caller
    # Extensible metadata fields
    summary: str = ""
    entry_points: list[str] = field(default_factory=list)
    architecture: str = ""
    components: list[str] = field(default_factory=list)
    dependencies: list[str] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)
