"""Request and response schemas for RE:Track (RefinedEngine Track) API commands.

Backward-compatibility facade: Re-exports application-owned DTOs from app.application.dto.
All new application logic and use cases must import directly from app.application.dto.
"""

from app.application.dto import (
    # Common
    ErrorResponse,
    # Context
    AgentContextRequest,
    AgentContextResponse,
    ContextResponse,
    GenerateContextRequest,
    # Indexing
    IndexRepositoryRequest,
    IndexRepositoryResponse,
    IndexedRepositoryListResponse,
    RepoArchInfo,
    RepoComponentInfo,
    RepositorySummaryInfo,
    # Repositories
    RepositoryCreateRequest,
    RepositoryListResponse,
    RepositoryResponse,
    ScanResultResponse,
    # Memory
    CognifyRequest,
    CognifyResponse,
    DashboardStats,
    DatasetDataItemsResponse,
    DatasetInfo,
    DatasetListResponse,
    ForgetDatasetRequest,
    ForgetDatasetResponse,
    MemoryDataItem,
    MemoryGraphEdge,
    MemoryGraphNode,
    MemoryGraphResponse,
    MemoryStatsResponse,
    MemoryVectorsResponse,
    VectorDatasetInfo,
    # Packages
    ContextPackageAppendRequest,
    ContextPackageListResponse,
    ContextPackageResponse,
    ContextPackageSaveRequest,
    # System
    AppSettingsResponse,
    BackendStatusResponse,
    CogneeSettingsRequest,
    DetailedHealthResponse,
    DiscoveredModelDTO,
    HealthResponse,
    ProviderDiscoveryRequest,
    ProviderDiscoveryResponse,
    ProviderStatusResponse,
    # Benchmarks
    BenchmarkResultItem,
    BenchmarkSuiteResponse,
)


__all__ = [
    "ErrorResponse",
    "GenerateContextRequest",
    "ContextResponse",
    "AgentContextRequest",
    "AgentContextResponse",
    "IndexRepositoryRequest",
    "IndexRepositoryResponse",
    "RepoArchInfo",
    "RepoComponentInfo",
    "RepositorySummaryInfo",
    "IndexedRepositoryListResponse",
    "RepositoryCreateRequest",
    "RepositoryResponse",
    "RepositoryListResponse",
    "ScanResultResponse",
    "ForgetDatasetRequest",
    "ForgetDatasetResponse",
    "DatasetInfo",
    "DatasetListResponse",
    "MemoryGraphNode",
    "MemoryGraphEdge",
    "MemoryGraphResponse",
    "VectorDatasetInfo",
    "MemoryVectorsResponse",
    "MemoryDataItem",
    "DatasetDataItemsResponse",
    "CognifyRequest",
    "CognifyResponse",
    "MemoryStatsResponse",
    "DashboardStats",
    "ContextPackageSaveRequest",
    "ContextPackageResponse",
    "ContextPackageListResponse",
    "ContextPackageAppendRequest",
    "HealthResponse",
    "BackendStatusResponse",
    "CogneeSettingsRequest",
    "AppSettingsResponse",
    "BenchmarkResultItem",
    "BenchmarkSuiteResponse",
]
